"""initial schema

Revision ID: 3cf1346f9f34
Revises: 
Create Date: 2026-08-24 15:23:14.930109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf1346f9f34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_tactics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attack_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attack_id')
    )
    op.create_table('attack_techniques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attack_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_subtechnique', sa.Boolean(), nullable=False),
    sa.Column('parent_technique_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_technique_id'], ['attack_techniques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attack_techniques', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attack_techniques_attack_id'), ['attack_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('engagements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technique_tactics',
    sa.Column('technique_id', sa.Integer(), nullable=False),
    sa.Column('tactic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tactic_id'], ['attack_tactics.id'], ),
    sa.ForeignKeyConstraint(['technique_id'], ['attack_techniques.id'], ),
    sa.PrimaryKeyConstraint('technique_id', 'tactic_id')
    )
    op.create_table('activity_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('occurred_started_at', sa.DateTime(), nullable=True),
    sa.Column('occurred_ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_entries_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('backup_destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('storage_type', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('endpoint_url', sa.String(length=255), nullable=True),
    sa.Column('bucket_or_resource', sa.String(length=255), nullable=True),
    sa.Column('account_identifier', sa.String(length=255), nullable=True),
    sa.Column('access_key_id', sa.String(length=255), nullable=True),
    sa.Column('secret_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_backup_at', sa.DateTime(), nullable=True),
    sa.Column('last_backup_status', sa.String(length=20), nullable=True),
    sa.Column('last_backup_message', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_destinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_destinations_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('credential_type', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('hash_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('api_key_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('ssh_private_key_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('ssh_passphrase_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('totp_secret_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('source_host', sa.String(length=255), nullable=True),
    sa.Column('access_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credentials_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('infrastructure_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('infrastructure_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_infrastructure_nodes_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('iocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=1000), nullable=True),
    sa.Column('hash_type', sa.String(length=20), nullable=True),
    sa.Column('hash_value', sa.String(length=128), nullable=True),
    sa.Column('dropped_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iocs_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('loot_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('encrypted_content', sa.LargeBinary(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('associated_host', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('sha256_plaintext', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loot_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loot_files_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('handoff_notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todos_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('finding_credential',
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('finding_id', 'credential_id')
    )
    op.create_table('finding_infra_node',
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('infra_node_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['infra_node_id'], ['infrastructure_nodes.id'], ),
    sa.PrimaryKeyConstraint('finding_id', 'infra_node_id')
    )
    op.create_table('finding_ioc',
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('ioc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], ),
    sa.PrimaryKeyConstraint('finding_id', 'ioc_id')
    )
    op.create_table('finding_loot',
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('loot_file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['loot_file_id'], ['loot_files.id'], ),
    sa.PrimaryKeyConstraint('finding_id', 'loot_file_id')
    )
    op.create_table('infrastructure_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['infrastructure_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['infrastructure_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('infrastructure_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_infrastructure_edges_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('infrastructure_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['infrastructure_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('infrastructure_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_infrastructure_services_node_id'), ['node_id'], unique=False)

    op.create_table('killchain_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('infra_node_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('occurred_ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['infra_node_id'], ['infrastructure_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('killchain_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_killchain_entries_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('finding_killchain_entry',
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('killchain_entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['killchain_entry_id'], ['killchain_entries.id'], ),
    sa.PrimaryKeyConstraint('finding_id', 'killchain_entry_id')
    )
    op.create_table('killchain_entry_loot',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('loot_file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['killchain_entries.id'], ),
    sa.ForeignKeyConstraint(['loot_file_id'], ['loot_files.id'], ),
    sa.PrimaryKeyConstraint('entry_id', 'loot_file_id')
    )
    op.create_table('technique_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.Integer(), nullable=False),
    sa.Column('loot_file_id', sa.Integer(), nullable=True),
    sa.Column('killchain_entry_id', sa.Integer(), nullable=True),
    sa.Column('mapped_by_id', sa.Integer(), nullable=False),
    sa.Column('mapped_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('(loot_file_id IS NOT NULL AND killchain_entry_id IS NULL) OR (loot_file_id IS NULL AND killchain_entry_id IS NOT NULL)', name='ck_technique_mapping_single_target'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['killchain_entry_id'], ['killchain_entries.id'], ),
    sa.ForeignKeyConstraint(['loot_file_id'], ['loot_files.id'], ),
    sa.ForeignKeyConstraint(['mapped_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['technique_id'], ['attack_techniques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technique_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technique_mappings_engagement_id'), ['engagement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technique_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technique_mappings_engagement_id'))

    op.drop_table('technique_mappings')
    op.drop_table('killchain_entry_loot')
    op.drop_table('finding_killchain_entry')
    with op.batch_alter_table('killchain_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_killchain_entries_engagement_id'))

    op.drop_table('killchain_entries')
    with op.batch_alter_table('infrastructure_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_infrastructure_services_node_id'))

    op.drop_table('infrastructure_services')
    with op.batch_alter_table('infrastructure_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_infrastructure_edges_engagement_id'))

    op.drop_table('infrastructure_edges')
    op.drop_table('finding_loot')
    op.drop_table('finding_ioc')
    op.drop_table('finding_infra_node')
    op.drop_table('finding_credential')
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todos_engagement_id'))

    op.drop_table('todos')
    with op.batch_alter_table('loot_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loot_files_engagement_id'))

    op.drop_table('loot_files')
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iocs_engagement_id'))

    op.drop_table('iocs')
    with op.batch_alter_table('infrastructure_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_infrastructure_nodes_engagement_id'))

    op.drop_table('infrastructure_nodes')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_engagement_id'))

    op.drop_table('findings')
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credentials_engagement_id'))

    op.drop_table('credentials')
    with op.batch_alter_table('backup_destinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_destinations_engagement_id'))

    op.drop_table('backup_destinations')
    with op.batch_alter_table('activity_log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_entries_engagement_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_entries_created_at'))

    op.drop_table('activity_log_entries')
    op.drop_table('technique_tactics')
    op.drop_table('engagements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('attack_techniques', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attack_techniques_attack_id'))

    op.drop_table('attack_techniques')
    op.drop_table('attack_tactics')
    # ### end Alembic commands ###
