"""add loot_files content_oid

Revision ID: d39a50a64c1b
Revises: 3cf1346f9f34
Create Date: 2026-08-24 16:35:51.137716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39a50a64c1b'
down_revision = '3cf1346f9f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loot_files', sa.Column('content_oid', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loot_files', 'content_oid')
    # ### end Alembic commands ###
